### ISSUE TITLE
Initialize new rails project

### ISSUE THREAD

**Issue by mluts** [Sontsevolosa/lunchez#1]
Don't use rspec, use default rails test framework.

Don't use turbolinks.

Rails are considered as initialized if you can run rails server and root page works.

**Comment by Sontsevolosa** [comment]
why I can't use SSH key for 'git push'?

**Comment by mluts** [comment]
@Sontsevolosa seems like your shell doesn't have connection with ssh-agent.

**Comment by Sontsevolosa** [comment]
@mluts why I should to remove 'turbolinks' gem? it makes following links in app faster...

**Comment by mluts** [comment]
@Sontsevolosa turbolinks can break your javascript code in subtle way, because each time when you click on some link on the page, turbolinks reloads whole page and all event listeners should be reinitialized. I don't sure if it plays nicely with bootstrap, taken from CDN

**Comment by Sontsevolosa** [comment]
Issue is resolved in #11 pull request
