### ISSUE TITLE
Add slim to the project

### ISSUE THREAD

**Issue by mluts** [Sontsevolosa/lunchez#10]
It will be better to do this before doing #8

**Comment by Sontsevolosa** [comment]
Why Slim and Haml are better than HTML?

**Comment by mluts** [comment]
@Sontsevolosa HTML is too verbose in my opinion. HAML or Slim have shorter code, hence easier for understanding/fixing/writing it. You can choose between slim and haml freely.

I choosed slim because it is a new trend, but it looks like haml on surface.

**Comment by Sontsevolosa** [comment]
@ can I close the issue?

**Comment by mluts** [comment]
@Sontsevolosa sure, detach "to-verify" and close

As a reminder: please write all views in "slim" format in future.

**Comment by Sontsevolosa** [comment]
Issue is resolved in #13 pull request
