### ISSUE TITLE
Remove password from database.yml. Rename database.yml to database.yml.example

### ISSUE THREAD

**Issue by mluts** [Sontsevolosa/lunchez#14]
It is bad to have database.yml committed to repository, because each developer has he's own database.yml, and no one wants accidentally commit their  user/password to the git.

**Comment by Sontsevolosa** [comment]
@mluts when I deleted password from [there](http://prntscr.com/bt67g8) I got this [error](http://prntscr.com/bt67wq). Note I can to enter to database with command `mysql -u root -p` and I can to manage a current database.

**Comment by Sontsevolosa** [comment]
@mluts did you mean I should to make operations with database.yml like with secrets.yml ?  I.e. after this operations database.yml should stay in my directory but be ignored by Git?

**Comment by mluts** [comment]
@Sontsevolosa yes, i wanted from you to remove `database.yml` from repository, but it can stay as ignored file in your `config` directory, including password. `password` should not be present in `database.yml.example`. `database.yml.example` can't contain any passwords because it is example.

**Comment by Sontsevolosa** [comment]
@mluts thank you very much) I understood everything) 🤓🐣🐸

**Comment by Sontsevolosa** [comment]
Issue is resolved in #24 pull request
