### ISSUE TITLE
Have a routing error when to link to "Sign out" in the header

### ISSUE THREAD

**Issue by Sontsevolosa** [Sontsevolosa/lunchez#25]
```No route matches [GET] "/users/sign_out"```

```Rails.root: /home/masya/Programming/lunchez```

```actionpack (4.2.5.1) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
actionpack (4.2.5.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
railties (4.2.5.1) lib/rails/rack/logger.rb:38:in `call_app'
railties (4.2.5.1) lib/rails/rack/logger.rb:20:in `block in call'
activesupport (4.2.5.1) lib/active_support/tagged_logging.rb:68:in `block in tagged'
activesupport (4.2.5.1) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (4.2.5.1) lib/active_support/tagged_logging.rb:68:in `tagged'
railties (4.2.5.1) lib/rails/rack/logger.rb:20:in `call'
actionpack (4.2.5.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
rack (1.6.4) lib/rack/runtime.rb:18:in `call'
activesupport (4.2.5.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
rack (1.6.4) lib/rack/lock.rb:17:in `call'
actionpack (4.2.5.1) lib/action_dispatch/middleware/static.rb:116:in `call'
rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
railties (4.2.5.1) lib/rails/engine.rb:518:in `call'
railties (4.2.5.1) lib/rails/application.rb:165:in `call'
rack (1.6.4) lib/rack/lock.rb:17:in `call'
rack (1.6.4) lib/rack/content_length.rb:15:in `call'
rack (1.6.4) lib/rack/handler/webrick.rb:88:in `service'
/home/masya/.rbenv/versions/2.3.0/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
/home/masya/.rbenv/versions/2.3.0/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
/home/masya/.rbenv/versions/2.3.0/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'```

Add a right configuration for a "Sign out" path in the header.
Add an integration test with PhantomJS for verifying a correct work of a link in the header.

**Comment by mluts** [comment]
@Sontsevolosa could you please attach exception message here? Backtrace would also be good, if you have it.

**Comment by Sontsevolosa** [comment]
@mluts please, review my changes in an issue description

**Comment by mluts** [comment]
@Sontsevolosa i don't understand when means 

> a right configuration for a "Sign out" path in the header.

you mean fixing broken link in page header ?

**Comment by mluts** [comment]
@Sontsevolosa thank you for clarifying issue description 👌

**Comment by mluts** [comment]
@Sontsevolosa advice: to fix the link, it should use "DELETE" method instead of get, this can be done by including jquery-ujs javascript plugin for rails and writing `link_to ..., method: :delete`

**Comment by Sontsevolosa** [comment]
@mluts my answers:

> you mean fixing broken link in page header ?

yes)

> thank you for clarifying issue description

you are welcome)

> advice: to fix the link, it should use "DELETE" method instead of get, this can be done by including jquery-ujs javascript plugin for rails and writing link_to ..., method: :delete

yes, I know) bigger problem for me will be test with Capybara)

**Comment by Sontsevolosa** [comment]
Issue is resolved in #26 pull request
