### ISSUE TITLE
Implement user authentication

### ISSUE THREAD

**Issue by mluts** [Sontsevolosa/lunchez#4]
User should have ability to authenticate himself through a html form.

Authentication here means, that after signing in into application i can have access to pages, that unauthenticated user doesn't have.

All pages within application should require authentication.

**Comment by Sontsevolosa** [comment]
@mluts how will user know that he is admin or user? 
or did you mean that admin is signing in human and user is not signing in human?

**Comment by Sontsevolosa** [comment]
Issue is resolved in #21 pull request
