### ISSUE TITLE
Make sign in form a default page for unauthenticated user

### ISSUE THREAD

**Issue by mluts** [Sontsevolosa/lunchez#5]

**Comment by Sontsevolosa** [comment]
@mluts I implemented it in Application Controller (I added 'before_action :authenticate_user!').
I think this is a solution for this issue.

**Comment by mluts** [comment]
@Sontsevolosa yes, this issue is already resolved

**Comment by Sontsevolosa** [comment]
@mluts  can I close this issue?

**Comment by mluts** [comment]
@Sontsevolosa sure

**Comment by Sontsevolosa** [comment]
Issue is resolved in comments
