### ISSUE TITLE
Implement user model

### ISSUE THREAD

**Issue by mluts** [Sontsevolosa/lunchez#7]
Include migration for creating user table

**Comment by Sontsevolosa** [comment]
Do you have special requirements for User table?

**Comment by mluts** [comment]
@Sontsevolosa i think that there should be at least first_name, last_name, email and role.

Email - for notifying and sign-in, first/last name for distinguishing users for admin.

I'd recommend to generate users table with devise gem, it will include all required columns for authenticating. You only should add "human" columns after that.

**Comment by Sontsevolosa** [comment]
@mluts what does it mean - "human columns"?

**Comment by mluts** [comment]
@Sontsevolosa i mean "first_name", "last_name" and so on. Things that are not primary for users table, like extra optional information.

**Comment by Sontsevolosa** [comment]
Issue is resolved in #20 pull request
